name: React CI - CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          heroku_app_name: xforceappf
          email: rubenchod22@gmail.com
          heroku_api_key: 87cf199e-ca38-4638-ae5f-dbc052261bfa
          # (Optionals)
          dockerfile_directory: algo aqui #NO estoy segura como va esto
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
